### ISSUE TITLE
Array json

### ISSUE THREAD

**Issue by annymsMthd** [rwaldron/jquery-hive#1]
I have an array in my json object and im getting this error when my worker tries to parse:

arg is undefined
http://localhost:64604/scripts/jquery.hive.pollen.js
Line 257

the worker code is:

importScripts('jquery.hive.pollen.js');
$(function (data) {
    $.ajax.post({
        url: "/Grid/Update",
        data:  $.param(data.message),
        success: function (msg) {
            return true;
        }
    });
});

And the object looks like:

var requestObject =
        {
            GridID: 1,
            StartIndex: 1,
            PageSize: 50,
            Search: "",
            Assigned: false,
            Outstanding: true,
            Columns: []
        };

**Comment by annymsMthd** [comment]
I was reading through the source and found my issue, $.param(data). Issue was entered in error.

**Comment by rwaldron** [comment]
Were you able to resolve the issue?
