### ISSUE TITLE
ajax post is by default sync in Chrome/Safari and async in other browsers

### ISSUE THREAD

**Issue by Ms2ger** [rwaldron/jquery-hive#7]
As first filed at http://code.google.com/p/thermetics-forum-extensions/issues/detail?id=32:

What steps will reproduce the problem?
1. Load http://stackoverflow.com/questions/8528610/web-workers-behave-differently-in-webkit-than-firefox
2. Debug to figure out why that happens
3. Cry

Please take out the user-agent sniffing and make the default behavior the same in all browsers!

**Comment by rwaldron** [comment]
Closed, see https://github.com/rwldrn/jquery-hive/pull/10
