### ISSUE TITLE
options.sync is backwards (true means to do an async request)

### ISSUE THREAD

**Issue by Ms2ger** [rwaldron/jquery-hive#8]
As first filed at http://code.google.com/p/thermetics-forum-extensions/issues/detail?id=33:

What steps will reproduce the problem?
1.  Try to do an ajax request with "sync: true" in options
2.  Observe that the request is async.

The code looks like this:

```
_xhr.open(options.type, options.url, options.sync); 
```

but the third argument to XMLHttpRequest open is whether the request should be _async_.

**Comment by rwaldron** [comment]
Closed, see https://github.com/rwldrn/jquery-hive/pull/10
