### ISSUE TITLE
remove browser sniffing 

### ISSUE THREAD

**Issue by ericjang** [rwaldron/jquery-hive#9]
Problem description here:

http://stackoverflow.com/questions/8528610/web-workers-behave-differently-in-webkit-than-firefox/8535673#8535673

question was resolved by switching 

sync : false

, but it would be nice if polen.js could have the same default behavior for all browsers to avoid confusion.

Thanks!

**Comment by rwaldron** [comment]
Agreed, completely. That was a terrible hack to fix a poorly assessed problem in Safari in 2009

**Comment by rwaldron** [comment]
I'm going to rename the prop to `async` (because that makes sense) and set it to `true`, (because that makes sense). Doing so passes the existing tests.
